mybatis:
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8081

logging:
  config: classpath:log4j2.xml

spring:
  config:
    import: nacos:warp-dev.yaml
  datasource:
    url: jdbc:mysql://localhost:3305/exchange
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: warp  # 服务名
  profiles:
    active: dev  # 环境隔离
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: ${spring.profiles.active}  # 环境隔离
        group: DEFAULT_GROUP
        ephemeral: true  # 是否临时实例(默认true)
      config:
        refresh:
          enabled: true
        server-addr: 127.0.0.1:8848
        namespace: ${spring.profiles.active}
        group: DEFAULT_GROUP
        file-extension: yaml  # 配置格式
        refresh-enabled: true  # 动态刷新
        shared-configs:  # 共享配置
          - data-id: common.yaml
            group: COMMON_GROUP
            refresh: true